# Generated by Django 5.0.2 on 2024-03-30 09:30

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcde12345', length=7, max_length=10, prefix='VEN', unique=True),
        ),
    ]
